language: python
python:
  - 3.7
  - 3.6
  - 3.5

cache: pip

env:
  global:
    - PIPENV_IGNORE_VIRTUALENVS=1
    - PIPENV_VENV_IN_PROJECT=1

install:
  - pip install pipenv
  - pipenv install --dev

script:
  - pipenv run flake8 broqer
  - pipenv run mypy broqer
  - pipenv run rstcheck README.rst
  - pipenv run py.test --doctest-modules --cov=broqer

after_success:
  - pipenv run codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: semiversus
  password:
    secure: WBixp3vHoCp6SgrjODUTMf3L5op/NHpLeNqk1Yg6bGBp9bw20FzicrsA57uD4CFDiI3v5yxeALwCOCy8iBVi8l6GR1H4eV2EsBWL+KqISm49pzIMTqxzHIVwYLVoFlzq9DF34YyZpY8fA0inqPxD2+2/EaEANlJnKQPbvTOebdEyKGsxdgNy7CqDb2BYSgoq5BzAThLP8jq/NMVdbgr46Xdi3mmaJMGXivbdPyeBlrShGY4pTiNnF0vtF5nktfEMh08gCcldHRsAyw2JMA+Hd6jeNNVWgkCW1uDWH1094gQiRf09V7HfIdmq67fqxAkmviK6vsqohAMbLf1R1iez7aW8RUTZz34281GDR/+qY+Nagwhe8AcW34XWnTzqcTNF5CTJLGftViFAT0hUlQ+w5bLnPT+/qzbqJumntSEzbJabUYMk7xHUKzSr6uYllRDqwwtDgVfqQT2FTkD8/F8GB6onkgXxCf1j3AwqcCC5w/tJ9LiTBnWPW5tWrRrGdYhmhKAXeeW3fZ5AOPbccMDbUWZWGMFOwCydcic71gx90VwRWegepFc+ORargjvCbJ0yFNefFbDOviZILyMisIuPFe+gvAHcfO3dPXRjXEqq4gzPlOtIFavvLlnH2g76uPol1OJ+Ni68U9+eJEAMn/NnDv10Np9Jjx98nOgliL401SA=
  on:
    tags: true
    repo: semiversus/python-broqer
    python: 3.5